spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate: 
      ddl-auto: create-drop
    properties:
      hibernate:
        formate_sql: true
        show_sql: true
        
logging:
  level:
    com.tutorial: debug
  
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
